services:
  # Next.js Application Service
  next-app:
    build: .
    container_name: next_delivery_app
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env

  # PostgreSQL Database Service
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - "127.0.0.1:5432:5432"
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Define the named volume for data persistence
volumes:
  postgres_data:
